Songs_by_Level={
    '7': [
        'Suomi',
        'inkar-usi',
        'Dream goes on',
        'Romance Wars',
        'Blossoms',
        'Moonlight of Sand Castle',
        'Clotho and the stargazer',
        'Paradise',
        'Brand new world',
        'Infinity Heaven',
        'Dement ~after legend~',
        'Rise',
        'Vexaria',
        'Fairytale',
        'Sayonara Hatsukoi'
    ],
    '8': [
        'Gekka (Short Version)',
        '1F√',
        'Vivid Theory',
        'Oblivia',
        'world.execute(me);',
        'Senkyou',
        'FREEF4LL',
        'Diode',
        'Tie me down gently',
        'Chelsea',
        'Particle Arts',
        'Dot to Dot feat. shully',
        'Antithese',
        'Grimheart',
        'Solitary Dream',
        'MERLIN',
        'Hall of Mirrors',
        'Hikari',
        'Purgatorium',
        'dropdead',
        'Maze No.9',
        'Bookmaker (2D Version)',
        'Call My Name feat. Yukacco',
        'Silent Rush',
        'next to you',
        'Journey',
        'Reinvent',
        'Surrender',
        'One Last Drive',
        'Rabbit In The Black Room',
        'Genesis',
        'Moonheart',
        'Harutopia ~Utopia of Spring~',
        "Evoltex (poppi'n mix)",
        'REconstruction',
        'Flashback',
        'Dandelion',
        'Lumia',
        'Relentless',
        'memoryfactory.lzh',
        "I've heard it said",
        'cry of viyella',
        'Babaroque',
        'Shades of Light in a Transcendent Realm',
        'Snow White',
        'Lucifer',
        'Vexaria',
        'Eccentric Tale',
        'Beside You'
    ],
    '9': [
        'Lapis',
        'CROSS†OVER',
        'MAHOROBA',
        'Teriqma',
        'Feels So Right feat. Renko',
        'Faint Light (Arcaea Edit)',
        'Give Me a Nightmare',
        'Equilibrium',
        'amygdata',
        "La'qryma of the Wasteland",
        'Avant Raze',
        'Monochrome Princess',
        'AI[UE]OON',
        'Vindication',
        'VECTOЯ',
        'ReviXy',
        'Libertas',
        'OMAKENO Stroke',
        'Empire of Winter',
        'Phantasia',
        'Astral tale',
        'Rugie',
        'STAGER (ALL STAGE CLEAR)',
        'Purgatorium',
        'LunarOrbit -believe in the Espebranch road-',
        'Fallensquare',
        'Illegal Paradise',
        'Be There',
        'Cybernecia Catharsis',
        'carmine:scythe',
        'Strongholds',
        'Blaster',
        'Specta',
        'Syro',
        'Yosakura Fubuki',
        'Iconoclast',
        'Red and Blue',
        "Dreamin' Attraction!!",
        'Auxesia',
        'Impure Bird',
        'Ignotus',
        'Oracle',
        'Your voice so... feat. Such',
        'CROSS†SOUL',
        'DataErr0r',
        'Kanagawa Cyber Culvert',
        'Chronostasis',
        'Party Vinyl',
        'Flyburg and Endroll',
        'Anokumene',
        'Infinity Heaven',
        'Essence of Twilight',
        'Lumia',
        'qualia -ideaesthesia-',
        'GOODTEK (Arcaea Edit)',
        'Lost Civilization',
        'Fairytale',
        "Alice's Suitcase",
        'Alice à la mode',
        'Jump',
        'Lazy Addiction'
    ],
    '9+': [
        'Xeraphinite',
        'Galaxy Friends',
        'Got hive of Ra',
        'BADTEK',
        'Scarlet Cage',
        'Altale',
        'Black Lotus',
        'Arcahv',
        'Lost Desire',
        'Antagonism',
        'BLRINK',
        'Einherjar Joker',
        'BATTLE NO.1',
        'Filament',
        'Heavenly caress',
        'A Wandering Melody of Love',
        'Heavensdoor',
        'Dreadnought',
        'SUPERNOVA',
        'Corruption',
        'Black Territory',
        'DX Choseinou Full Metal Shojo',
        'Linear Accelerator',
        'Nhelv',
        'Sulfur',
        'The Message',
        'Memory Forest',
        'Quon',
        'SOUNDWiTCH',
        'Lethaeus',
        'Dement ~after legend~',
        'GOODTEK (Arcaea Edit)',
        "Heart Jackin'",
        'Dazzle hop'
    ],
    '10': [
        'Xanatos',
        'Malicious Mischance',
        'Tempestissimo',
        'corps-sans-organes',
        'IZANA',
        'GLORY：ROAD',
        'Mirzam',
        'Valhalla:0',
        'Ikazuchi',
        'Garakuta Doll Play',
        'Vicious Heroism',
        'Scarlet Lance',
        'Tiferet',
        'Alexandrite',
        'Ether Strike',
        'γuarδina',
        'Metallic Punisher',
        'cyanine',
        'conflict',
        'trappola bewitching',
        'Modelista',
        'αterlβus',
        'Nirv lucE',
        'Sheriruth',
        'PRAGMATISM',
        'Felis',
        'To: Alice Liddell',
        'Viyella’s Tears'
    ],
    '10+': [
        'BUCHiGiRE Berserker',
        '#1f1e33',
        'Dantalion',
        'Ringed Genesis',
        'World Vanquisher',
        'Cyaegha',
        'ouroboros -twin stroke of the end-',
        'Halcyon',
        'Singularity',
        'Axium Crisis',
        'ω4'
    ],
    '11': [
        'Tempestissimo',
        'SAIKYO STRONGER',
        'Fracture Ray',
        'Grievous Lady'
    ]
}

Songs=[   
    {'name': 'Xanatos', 'level': '10'},    
    {'name': 'Xeraphinite', 'level': '9+'},
    {'name': 'Lapis', 'level': '9'},       
    {'name': 'CROSS†OVER', 'level': '9'},  
    {'name': 'Galaxy Friends', 'level': '9+'},
    {'name': 'BUCHiGiRE Berserker', 'level': '10+'},
    {'name': 'Got hive of Ra', 'level': '9+'},
    {'name': 'Malicious Mischance', 'level': '10'},
    {'name': 'BADTEK', 'level': '9+'},
    {'name': 'MAHOROBA', 'level': '9'},
    {'name': 'Teriqma', 'level': '9'},
    {'name': 'Scarlet Cage', 'level': '9+'},
    {'name': 'Feels So Right feat. Renko', 'level': '9'},
    {'name': 'Faint Light (Arcaea Edit)', 'level': '9'},
    {'name': 'Altale', 'level': '9+'},
    {'name': 'Black Lotus', 'level': '9+'},
    {'name': 'Give Me a Nightmare', 'level': '9'},
    {'name': 'Gekka (Short Version)', 'level': '8'},
    {'name': '1F√', 'level': '8'},
    {'name': 'Vivid Theory', 'level': '8'},
    {'name': 'Arcahv', 'level': '9+'},
    {'name': 'Tempestissimo', 'level': '10'},
    {'name': 'Tempestissimo', 'level': '11'},
    {'name': '#1f1e33', 'level': '10+'},
    {'name': 'Dantalion', 'level': '10+'},
    {'name': 'Lost Desire', 'level': '9+'},
    {'name': 'Antagonism', 'level': '9+'},
    {'name': 'Equilibrium', 'level': '9'},
    {'name': 'corps-sans-organes', 'level': '10'},
    {'name': 'amygdata', 'level': '9'},
    {'name': 'Oblivia', 'level': '8'},
    {'name': 'BLRINK', 'level': '9+'},
    {'name': 'world.execute(me);', 'level': '8'},
    {'name': 'SAIKYO STRONGER', 'level': '11'},
    {'name': 'IZANA', 'level': '10'},
    {'name': 'Einherjar Joker', 'level': '9+'},
    {'name': "La'qryma of the Wasteland", 'level': '9'},
    {'name': 'BATTLE NO.1', 'level': '9+'},
    {'name': 'Avant Raze', 'level': '9'},
    {'name': 'Filament', 'level': '9+'},
    {'name': 'Senkyou', 'level': '8'},
    {'name': 'Heavenly caress', 'level': '9+'},
    {'name': 'Monochrome Princess', 'level': '9'},
    {'name': 'GLORY：ROAD', 'level': '10'},
    {'name': 'FREEF4LL', 'level': '8'},
    {'name': 'Diode', 'level': '8'},
    {'name': 'Mirzam', 'level': '10'},
    {'name': 'Valhalla:0', 'level': '10'},
    {'name': 'Tie me down gently', 'level': '8'},
    {'name': 'A Wandering Melody of Love', 'level': '9+'},
    {'name': 'AI[UE]OON', 'level': '9'},
    {'name': 'Chelsea', 'level': '8'},
    {'name': 'Ringed Genesis', 'level': '10+'},
    {'name': 'Heavensdoor', 'level': '9+'},
    {'name': 'Vindication', 'level': '9'},
    {'name': 'Particle Arts', 'level': '8'},
    {'name': 'Dreadnought', 'level': '9+'},
    {'name': 'World Vanquisher', 'level': '10+'},
    {'name': 'Ikazuchi', 'level': '10'},
    {'name': 'Garakuta Doll Play', 'level': '10'},
    {'name': 'Dot to Dot feat. shully', 'level': '8'},
    {'name': 'SUPERNOVA', 'level': '9+'},
    {'name': 'VECTOЯ', 'level': '9'},
    {'name': 'Cyaegha', 'level': '10+'},
    {'name': 'Vicious Heroism', 'level': '10'},
    {'name': 'Corruption', 'level': '9+'},
    {'name': 'Black Territory', 'level': '9+'},
    {'name': 'Antithese', 'level': '8'},
    {'name': 'ReviXy', 'level': '9'},
    {'name': 'Grimheart', 'level': '8'},
    {'name': 'Solitary Dream', 'level': '8'},
    {'name': 'Libertas', 'level': '9'},
    {'name': 'ouroboros -twin stroke of the end-', 'level': '10+'},
    {'name': 'Scarlet Lance', 'level': '10'},
    {'name': 'OMAKENO Stroke', 'level': '9'},
    {'name': 'DX Choseinou Full Metal Shojo', 'level': '9+'},
    {'name': 'MERLIN', 'level': '8'},
    {'name': 'Empire of Winter', 'level': '9'},
    {'name': 'Phantasia', 'level': '9'},
    {'name': 'Astral tale', 'level': '9'},
    {'name': 'Rugie', 'level': '9'},
    {'name': 'Tiferet', 'level': '10'},
    {'name': 'Linear Accelerator', 'level': '9+'},
    {'name': 'STAGER (ALL STAGE CLEAR)', 'level': '9'},
    {'name': 'Hall of Mirrors', 'level': '8'},
    {'name': 'Hikari', 'level': '8'},
    {'name': 'Alexandrite', 'level': '10'},
    {'name': 'Purgatorium', 'level': '8'},
    {'name': 'Purgatorium', 'level': '9'},
    {'name': 'LunarOrbit -believe in the Espebranch road-', 'level': '9'},
    {'name': 'Fallensquare', 'level': '9'},
    {'name': 'dropdead', 'level': '8'},
    {'name': 'Nhelv', 'level': '9+'},
    {'name': 'Fracture Ray', 'level': '11'},
    {'name': 'Ether Strike', 'level': '10'},
    {'name': 'Halcyon', 'level': '10+'},
    {'name': 'Sulfur', 'level': '9+'},
    {'name': 'The Message', 'level': '9+'},
    {'name': 'Maze No.9', 'level': '8'},
    {'name': 'Illegal Paradise', 'level': '9'},
    {'name': 'Bookmaker (2D Version)', 'level': '8'},
    {'name': 'Suomi', 'level': '7'},
    {'name': 'Call My Name feat. Yukacco', 'level': '8'},
    {'name': 'inkar-usi', 'level': '7'},
    {'name': 'Be There', 'level': '9'},
    {'name': 'Cybernecia Catharsis', 'level': '9'},
    {'name': 'γuarδina', 'level': '10'},
    {'name': 'carmine:scythe', 'level': '9'},
    {'name': 'Singularity', 'level': '10+'},
    {'name': 'Memory Forest', 'level': '9+'},
    {'name': 'Strongholds', 'level': '9'},
    {'name': 'Silent Rush', 'level': '8'},
    {'name': 'next to you', 'level': '8'},
    {'name': 'Blaster', 'level': '9'},
    {'name': 'Metallic Punisher', 'level': '10'},
    {'name': 'cyanine', 'level': '10'},
    {'name': 'Quon', 'level': '9+'},
    {'name': 'Journey', 'level': '8'},
    {'name': 'Specta', 'level': '9'},
    {'name': 'Dream goes on', 'level': '7'},
    {'name': 'Syro', 'level': '9'},
    {'name': 'Reinvent', 'level': '8'},
    {'name': 'Yosakura Fubuki', 'level': '9'},
    {'name': 'Surrender', 'level': '8'},
    {'name': 'Grievous Lady', 'level': '11'},
    {'name': 'Axium Crisis', 'level': '10+'},
    {'name': 'conflict', 'level': '10'},
    {'name': 'trappola bewitching', 'level': '10'},
    {'name': 'SOUNDWiTCH', 'level': '9+'},
    {'name': 'Iconoclast', 'level': '9'},
    {'name': 'Red and Blue', 'level': '9'},
    {'name': "Dreamin' Attraction!!", 'level': '9'},
    {'name': 'One Last Drive', 'level': '8'},
    {'name': 'Modelista', 'level': '10'},
    {'name': 'Rabbit In The Black Room', 'level': '8'},
    {'name': 'Auxesia', 'level': '9'},
    {'name': 'Lethaeus', 'level': '9+'},
    {'name': 'Genesis', 'level': '8'},
    {'name': 'Moonheart', 'level': '8'},
    {'name': 'Romance Wars', 'level': '7'},
    {'name': 'Blossoms', 'level': '7'},
    {'name': 'Harutopia ~Utopia of Spring~', 'level': '8'},
    {'name': 'Impure Bird', 'level': '9'},
    {'name': 'Ignotus', 'level': '9'},
    {'name': 'αterlβus', 'level': '10'},
    {'name': 'Oracle', 'level': '9'},
    {'name': "Evoltex (poppi'n mix)", 'level': '8'},
    {'name': 'REconstruction', 'level': '8'},
    {'name': 'Moonlight of Sand Castle', 'level': '7'},
    {'name': 'Clotho and the stargazer', 'level': '7'},
    {'name': 'Your voice so... feat. Such', 'level': '9'},
    {'name': 'CROSS†SOUL', 'level': '9'},
    {'name': 'DataErr0r', 'level': '9'},
    {'name': 'Kanagawa Cyber Culvert', 'level': '9'},
    {'name': 'Chronostasis', 'level': '9'},
    {'name': 'Nirv lucE', 'level': '10'},
    {'name': 'Party Vinyl', 'level': '9'},
    {'name': 'Flyburg and Endroll', 'level': '9'},
    {'name': 'Flashback', 'level': '8'},
    {'name': 'Paradise', 'level': '7'},
    {'name': 'Brand new world', 'level': '7'},
    {'name': 'Anokumene', 'level': '9'},
    {'name': 'Infinity Heaven', 'level': '7'},
    {'name': 'Infinity Heaven', 'level': '9'},
    {'name': 'Dement ~after legend~', 'level': '7'},
    {'name': 'Dement ~after legend~', 'level': '9+'},
    {'name': 'Dandelion', 'level': '8'},
    {'name': 'Sheriruth', 'level': '10'},
    {'name': 'PRAGMATISM', 'level': '10'},
    {'name': 'Essence of Twilight', 'level': '9'},
    {'name': 'Lumia', 'level': '8'},
    {'name': 'Lumia', 'level': '9'},
    {'name': 'Relentless', 'level': '8'},
    {'name': 'memoryfactory.lzh', 'level': '8'},
    {'name': "I've heard it said", 'level': '8'},
    {'name': 'cry of viyella', 'level': '8'},
    {'name': 'qualia -ideaesthesia-', 'level': '9'},
    {'name': 'GOODTEK (Arcaea Edit)', 'level': '9'},
    {'name': 'GOODTEK (Arcaea Edit)', 'level': '9+'},
    {'name': 'Lost Civilization', 'level': '9'},
    {'name': 'Babaroque', 'level': '8'},
    {'name': 'Shades of Light in a Transcendent Realm', 'level': '8'},
    {'name': 'Snow White', 'level': '8'},
    {'name': 'Lucifer', 'level': '8'},
    {'name': 'Rise', 'level': '7'},
    {'name': 'Vexaria', 'level': '7'},
    {'name': 'Vexaria', 'level': '8'},
    {'name': 'Fairytale', 'level': '7'},
    {'name': 'Fairytale', 'level': '9'},
    {'name': 'Sayonara Hatsukoi', 'level': '7'},
    {'name': 'Eccentric Tale', 'level': '8'},
    {'name': "Alice's Suitcase", 'level': '9'},
    {'name': 'Alice à la mode', 'level': '9'},
    {'name': 'Jump', 'level': '9'},
    {'name': 'Felis', 'level': '10'},
    {'name': 'Beside You', 'level': '8'},
    {'name': "Heart Jackin'", 'level': '9+'},
    {'name': 'To: Alice Liddell', 'level': '10'},
    {'name': 'Lazy Addiction', 'level': '9'},
    {'name': 'Dazzle hop', 'level': '9+'},
    {'name': 'Viyella’s Tears', 'level': '10'},
    {'name': 'ω4', 'level': '10+'}
]

Songs_meme={
        'Conflict':
            '주오르히~~↑ㅋㅋㅋㅋ뷔얀타스ㅋㅋㅋㅋㅋ와스 페스트ㅋㅋㅋㅋㅋㅋㅋ루오르ㅋㅋ\
ㅋㅋㅋ프로이 유크ㅋㅋㅋㅋㅋㅋㅋ달페\
수오이붜ㅋㅋㅋㅋㅋ쉔네ㅋㅋㅋㅋ얏 부 혠브가ㄹ죠ㅈ고아ㅈ가오가옼가ㅋㅋㅋ쟈 ㄱㅈㅈ',

        'Arcahv':
            '이이이~~↑ㅋㅋㅋㅋ켈렙조ㅋㅋㅋㅋㅋ이가아아 ㅋㅋㅋㅋㅋㅋㅋ칼라 케라ㅋㅋㅋㅋ\
ㅋ아카리자 ㅋㅋ셀러 이저ㅋㅋㅋㅋㅋㅋㅋ갠히 그커잴리ㅋㅋㅋㅋㅋ커신느ㅋㅋㅋㅋ벨러 포러잦\
    인ㅈ ㅈ라ㅈㅋㅋ러ㄱㅈㅈ',

        'crossover':
            '끝없이~~↑ㅋㅋㅋㅋㅋ이어진ㅋㅋㅋㅋ 상처들과ㅋㅋㅋㅋㅋㅋㅋㅋ끝없이 이어진\
ㅋㅋㅋㅋㅋㅋㅋㅋ인연들이ㅋㅋㅋㅋㅋ날 잇고 ㅋㅋㅋㅋㅋ나에게 ㅋㅋㅋㅋㅋㅋ주어진 시간들이\
    ㅋㅋㅋ물밀듯이 ㅋㅋㅋㅋㅋㅋ다시 흐르오좌ㅈ가윰ㅎ터둬럴ㅋㅋㅋㅋㅋㄱ'
    }

Ssongs={
    "Tempestissimo":
    "이 길은 인류에 대한 최악의 기억으로 불타버렸고,\
이 길의 끝에는, 항상 최후가 있을 것이다.\n**Tempestissimo**",
    "Arcahv":
    "모든 것을 파괴하는 재난에 대한 그녀의 의견은\
단 한마디로 전해졌다.\n“아름다워.”\n**Arcahv**",
    "ω4":
    "ω4\n냐후냐후타임~(ฅ^･ω･^ ฅ)"

}

BotCommands={
    "대립이 선곡 [레벨]":
    "레벨에 따른 곡을 선곡해드려요. ex)대립이 선곡 11",

    "대립이 패치노트":
    "최신 패치노트를 보여드려요.",

    "대립이 아르케아!":
    "아☆르☆케☆아",

    "대립이 주오르히":
    "in a desperate conflict, with a ruthless enemy...",

    "대립이 이어진":
    "하얗던 너의 마음이 나를 잇고 잊었던 나의 감정이 요동치네..."

    
}
patchnote="Arcaea 3.4.0\n- 새로운 콜라보팩 O.N.G.E.K.I. Collaboration (신곡 4곡과 새로운 파트너 루나 & 미아 )\n - 무작위 곡 선택 기능 개선\n - 다양한 부분의 UI 개선 "